INSERT INTO courses (name, description, short_description, image_filename, price, user_id)
VALUES
('Curso Avançado', 'Mussum Ipsum, cacilds vidis litro abertis. Quem num gosta di mé, boa gentis num é. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.', 'Mussum Ipsum 1 Curso Avançado com descrição curta.', 'demo_1.jpg', 29.99, 1),
('Curso Intermediário', 'Mussum Ipsum, cacilds vidis litro abertis. Quem num gosta di mé, boa gentis num é. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.', 'Mussum Ipsum 2 Curso Intermediário com descrição curta.', 'demo_2.jpg', 19.99, 1),
('Curso Básico', 'Mussum Ipsum, cacilds vidis litro abertis. Quem num gosta di mé, boa gentis num é. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.', 'Mussum Ipsum 3 Curso Básico com descrição curta.', 'demo_3.jpg', 39.99 , 1),
('Curso Intensivo', 'Mussum Ipsum, cacilds vidis litro abertis. Quem num gosta di mé, boa gentis num é. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.', 'Mussum Ipsum 4 Curso Intensivo com descrição curta.', 'demo_4.jpg', 49.99, 1),
('Curso Prático', 'Mussum Ipsum, cacilds vidis litro abertis. Quem num gosta di mé, boa gentis num é. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.', 'Mussum Ipsum 5 Curso Prático com descrição curta.', 'demo_5.jpg', 59.99, 1),
('Curso Avançado II', 'Mussum Ipsum, cacilds vidis litro abertis. Quem num gosta di mé, boa gentis num é. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.', 'Mussum Ipsum 6 Curso Avançado II com descrição curta.', 'demo_6.jpg', 69.99, 1),
('Curso Intermediário II', 'Mussum Ipsum, cacilds vidis litro abertis. Quem num gosta di mé, boa gentis num é. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.', 'Mussum Ipsum 7 Curso Intermediário II com descrição curta.', 'demo_7.jpg', 79.99, 1),
('Curso Avançado III', 'Mussum Ipsum, cacilds vidis litro abertis. Quem num gosta di mé, boa gentis num é. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.', 'Mussum Ipsum 8 Curso Avançado III com descrição curta.', 'demo_8.jpg', 89.99, 1),
('Curso Intermediário III', 'Mussum Ipsum, cacilds vidis litro abertis. Quem num gosta di mé, boa gentis num é. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.', 'Mussum Ipsum 9 Curso Intermediário III com descrição curta.', 'demo_9.jpg', 99.99, 1),
('Curso Avançado IV', 'Mussum Ipsum, cacilds vidis litro abertis. Quem num gosta di mé, boa gentis num é. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.', 'Mussum Ipsum 10 Curso Avançado IV com descrição curta.', 'demo_10.jpg', 109.99, 1);
